### ISSUE TITLE
Random fail when running tests in CI - timeout and max_retries

### ISSUE THREAD

**Issue by alallema** [meilisearch/meilisearch-ruby#168]
**Description**
The test `MeiliSearch allows to set a custom timeout and max_retries` happens to fail randomly, though quite rarely.

**Current behavior**
- This fail never happens in local on mac os x.
- Seen multiple time with Linux ubuntu VM cf: Environment
- One time from now on CI

**Logs**
<details>
    <summary>Expand to see logs</summary>

```
MeiliSearch
  has a version number
  raises an exception when it is impossible to connect
  allows to set a custom timeout and max_retries (FAILED - 1)

Failures:

  1) MeiliSearch allows to set a custom timeout and max_retries
     Failure/Error:
       expect do
         client.indexes
       end.to raise_error(Timeout::Error)

       expected Timeout::Error but nothing was raised
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-support-3.10.2/lib/rspec/support.rb:102:in `block in <module:Support>'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-support-3.10.2/lib/rspec/support.rb:111:in `notify_failure'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:40:in `handle_failure'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/expectation_target.rb:101:in `to'
     # ./spec/meilisearch_spec.rb:17:in `block (2 levels) in <top (required)>'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/rspec:23:in `load'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/rspec:23:in `<top (required)>'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/bundle:23:in `load'
     # /opt/hostedtoolcache/Ruby/2.6.7/x64/bin/bundle:23:in `<main>'

Finished in 2.61 seconds (files took 0.34938 seconds to load)
162 examples, 1 failure

Failed examples:

rspec ./spec/meilisearch_spec.rb:15 # MeiliSearch allows to set a custom timeout and max_retries
```
</details>

**Environment**
- OS: ubuntu 20.04
- Meilisearch: v0.20.0
- Ruby: 2.6.7

**Suggestion**
- This test fail every time if we use `timeout: 1`, because the client doesn't have _time_ to timeout before receiving the server  response:
```rb
  it 'allows to set a custom timeout and max_retries' do
    client = MeiliSearch::Client.new($URL, $MASTER_KEY, timeout: 1, max_retries: 2)
    expect do
      client.indexes
    end.to raise_error(Timeout::Error)
  end
```
It happens when `timeout: 0` for the same reason.

**Comment by curquiza** [comment]
This random failure happens really often and it becomes not convenient to work on this repo because of this.
We might think about deleting (by commenting) this test and creating an issue to better handle this kind of test (mocking?)

**Comment by curquiza** [comment]
Checked with @alallema and @bidoubiwa, we decided to disable this test for the moment, see #179
