### ISSUE TITLE
cannot load such file `meilisearch/utils`

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-ruby#268]
I now get 

```bash
Traceback (most recent call last):
	3: from test.rb:4:in `<main>'
	2: from test.rb:4:in `require'
	1: from /Users/curquiza/.rvm/gems/ruby-2.6.6/gems/meilisearch-0.17.1/lib/meilisearch.rb:4:in `<top (required)>'
/Users/curquiza/.rvm/gems/ruby-2.6.6/gems/meilisearch-0.17.1/lib/meilisearch.rb:4:in `require': cannot load such file -- meilisearch/utils (LoadError)
```

when trying to use v0.17.1 😅

**Comment by curquiza** [comment]
@brunoocasali FYI, we forgot to add the `utils.rb` file in the gemspec file 😅 😂 
I don't know if there is a way to avoid this mistake in the future?

**Comment by brunoocasali** [comment]
> @brunoocasali FYI, we forgot to add the `utils.rb` file in the gemspec file 😅 😂 I don't know if there is a way to avoid this mistake in the future, do you?

ouch :/

Yes, we could use a wildcard in `Dir` like devise do: https://github.com/heartcombo/devise/blob/main/devise.gemspec#L26
