### ISSUE TITLE
MeiliSearch::TimeoutError

### ISSUE THREAD

**Issue by drougojrom** [meilisearch/meilisearch-ruby#436]
**Description**
After I send a search request with the following params (below), I get `MeiliSearch::TimeoutError` from both meilisearch rails and ruby libraries.

```
{
  "offset": 0,
  "limit": 5,
  "attributesToHighlight": [
    "title",
    "description",
    "authors_simple"
  ],
  "filters": "territories=US AND (language=en)",
  "q": "I will always write be"
}
```

**Expected behavior**
Search should return a proper result.

**Current behavior**

```
/home/deployer/proxy_search/shared/bundle/ruby/3.1.0/gems/meilisearch-0.22.0/lib/meilisearch/http_request.rb:113:in `rescue in send_request': The request was not processed in the expected time. Net::ReadTimeout with #<TCPSocket:(closed)> (MeiliSearch::TimeoutError)                        
/home/deployer/proxy_search/shared/bundle/ruby/3.1.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:229:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
```

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Meilisearch version: 1.1.0     
- meilisearch-ruby version: v0.22.0

**Comment by brunoocasali** [comment]
Hi @drougojrom!

Does this problem also happen when you make the same request by cURL? I'm considering this can be an engine issue. With this information, it will be easier to understand it.
Also, if possible, how big are these documents where you're searching, and can you share RAM/Disk (used/available) sizes with me?

**Comment by drougojrom** [comment]
Ofc

1. Yes, you might be right here. Ruby lib, as far as I can see, basically sends the request directly to the engine.
2. 8 CPUs, 16gb RAM, 80 GB Disk, 60% free space.

**Comment by brunoocasali** [comment]
@oluademola I'll let you decide if is better to move it to the engine side or deal it here :)

**Comment by oluademola** [comment]
Hello @brunoocasali. Feel free to transfer it since it seems to be reproducible via a direct request to meilisearch. @drougojrom, thank you for the report, and sorry for the inconvenience. Since the problem seems to be very specific, I'd like to have a small piece of a dataset in order to reproduce it. Also, your index settings config will be very helpful.
